version: '3'
services:
  postgres:
    container_name: postgres_blood
    image: postgres:latest
    environment:
      POSTGRES_DB: blood_donation
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      -  postgres-data:/var/lib/postgresql/data
      - ./postgres:/docker-entrypoint-initdb.d/

  mongodb:
    container_name: mongo_blood
    image: mongo
    volumes:
      - mongodb-data:/data/db
      - ./mongo:/docker-entrypoint-initdb.d/
    ports:
      - "27017:27017"

volumes:
  postgres-data:
  mongodb-data: